name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build WildFly WAR
        run: |
          chmod +x ./first-service/gradlew ./second-service/gradlew
          cd first-service
          ./gradlew assemble -x test

      - name: Build Payara WAR
        run: |
          chmod +x ./first-service/gradlew ./second-service/gradlew
          cd second-service
          ./gradlew assemble -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build WildFly image
        run: docker build -t femeepohua/fergoeqs:wildfly-latest -f ./first-service/Dockerfile-wildfly ./first-service

      - name: Push WildFly image
        run: docker push femeepohua/fergoeqs:wildfly-latest

      - name: Build Payara image
        run: docker build -t femeepohua/fergoeqs:payara-latest -f ./second-service/Dockerfile-payara ./second-service

      - name: Push Payara image
        run: docker push femeepohua/fergoeqs:payara-latest

      - name: Build Frontend/Nginx image
        run: docker build -t femeepohua/fergoeqs:frontend-latest -f ./nginx/Dockerfile-nginx ./nginx

      - name: Push Frontend/Nginx image
        run: docker push femeepohua/fergoeqs:frontend-latest

      - name: Trigger deploy on VPS
        run: curl -X POST http://138.124.89.175:9000/hooks/auto-deploy
